package store

import (
	"database/sql"
	"errors"
	"path/filepath"
	"time"

	"github.com/happyarch/stigmergy/internal/serr"
)

// Root activity TTL: a root that has not been heard from in this long is
// treated as gone, and its claims stop blocking anyone. This is what makes a
// crashed agent self-healing rather than a permanent lock.
const RootTTL = 3600 * time.Second

// StaleRootAge is when a silent root gets its ended_at stamped for good, during
// opportunistic cleanup.
const StaleRootAge = 7 * 24 * time.Hour

// AgentKinds is the closed set enforced by the schema.
var AgentKinds = []string{"claude-code", "codex"}

// ErrNoRoot reports an unknown or already-ended root.
var ErrNoRoot = errors.New("store: root not found")

// Root is a registered top-level agent session.
type Root struct {
	RootID       string `json:"root_id"`
	AgentKind    string `json:"agent_kind"`
	SessionLabel string `json:"session_label,omitempty"`
	Worktree     string `json:"worktree"`
	Branch       string `json:"branch,omitempty"`
	RegisteredAt string `json:"registered_at"`
	LastSeenAt   string `json:"last_seen_at"`
}

// RootTTLCutoff is the last_seen_at below which a root counts as inactive. It
// appears in every active-claim predicate.
func RootTTLCutoff() string { return Stamp(NowTime().Add(-RootTTL)) }

// Registration is a root_register request.
type Registration struct {
	RootID       string // pre-generated by the caller (internal/ids)
	AgentKind    string
	Worktree     string
	Branch       string
	SessionLabel string
}

func (r Registration) validate() error {
	if !contains(AgentKinds, r.AgentKind) {
		return serr.E(serr.InvalidInput, "agent_kind %q is invalid: must be \"claude-code\" or \"codex\"", r.AgentKind)
	}
	if !filepath.IsAbs(r.Worktree) {
		return serr.E(serr.InvalidInput, "worktree must be an absolute path, got %q", r.Worktree)
	}
	return nil
}

func contains(set []string, v string) bool {
	for _, s := range set {
		if s == v {
			return true
		}
	}
	return false
}

const rootCols = `root_id, agent_kind, COALESCE(session_label, ''), worktree, COALESCE(branch, ''), registered_at, last_seen_at`

func scanRoot(row interface{ Scan(...any) error }) (*Root, error) {
	var r Root
	err := row.Scan(&r.RootID, &r.AgentKind, &r.SessionLabel, &r.Worktree, &r.Branch, &r.RegisteredAt, &r.LastSeenAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrNoRoot
	}
	if err != nil {
		return nil, serr.Internalf(err, "failed to read root")
	}
	return &r, nil
}

// RegisterRoot creates a root, or resumes an existing one.
//
// Resume is not an optimization: hosts restart the MCP server process mid
// session (Claude on /clear, Codex on compact), and a fresh root_id each time
// would strand the previous root's claims — live, unreleasable, blocking every
// other agent until TTL. Matching on (agent_kind, worktree, session_label)
// reconnects the session to the claims it already owns. An empty session_label
// cannot be matched on, so it always mints a new root.
func (d *DB) RegisterRoot(reg Registration) (root *Root, resumed bool, err error) {
	if err := reg.validate(); err != nil {
		return nil, false, err
	}
	tx, err := d.Begin()
	if err != nil {
		return nil, false, serr.Internalf(err, "failed to begin transaction")
	}
	defer tx.Rollback()

	now := Now()
	if reg.SessionLabel != "" {
		existing, err := scanRoot(tx.QueryRow(
			`SELECT `+rootCols+` FROM roots
			  WHERE agent_kind = ? AND worktree = ? AND session_label = ?
			    AND ended_at IS NULL AND last_seen_at > ?
			  ORDER BY registered_at DESC LIMIT 1`,
			reg.AgentKind, reg.Worktree, reg.SessionLabel, RootTTLCutoff()))
		switch {
		case err == nil:
			if _, err := tx.Exec(`UPDATE roots SET last_seen_at = ?, branch = ? WHERE root_id = ?`,
				now, nullStr(reg.Branch), existing.RootID); err != nil {
				return nil, false, serr.Internalf(err, "failed to refresh root")
			}
			if err := audit(tx, AuditEntry{
				Actor: existing.RootID, AgentKind: reg.AgentKind, Action: "root_resume",
				Target: reg.Worktree, Detail: "session_label=" + reg.SessionLabel,
			}); err != nil {
				return nil, false, serr.Internalf(err, "failed to write audit record")
			}
			if err := tx.Commit(); err != nil {
				return nil, false, serr.Internalf(err, "failed to commit root resume")
			}
			existing.LastSeenAt, existing.Branch = now, reg.Branch
			return existing, true, nil
		case errors.Is(err, ErrNoRoot): // fall through to create
		default:
			return nil, false, err
		}
	}

	if _, err := tx.Exec(
		`INSERT INTO roots(root_id, agent_kind, session_label, worktree, branch, registered_at, last_seen_at)
		 VALUES(?, ?, ?, ?, ?, ?, ?)`,
		reg.RootID, reg.AgentKind, nullStr(reg.SessionLabel), reg.Worktree, nullStr(reg.Branch), now, now,
	); err != nil {
		return nil, false, serr.Internalf(err, "failed to register root")
	}
	if err := audit(tx, AuditEntry{
		Actor: reg.RootID, AgentKind: reg.AgentKind, Action: "root_register",
		Target: reg.Worktree, Detail: "session_label=" + reg.SessionLabel,
	}); err != nil {
		return nil, false, serr.Internalf(err, "failed to write audit record")
	}
	if err := tx.Commit(); err != nil {
		return nil, false, serr.Internalf(err, "failed to commit root registration")
	}
	return &Root{
		RootID: reg.RootID, AgentKind: reg.AgentKind, SessionLabel: reg.SessionLabel,
		Worktree: reg.Worktree, Branch: reg.Branch, RegisteredAt: now, LastSeenAt: now,
	}, false, nil
}

// GetRoot returns an active root by id.
// ActiveRoots lists the roots currently working in this project: registered, not
// ended, and heard from within the root TTL. The same liveness test the claim
// predicate uses, so what `stigmergy watch` shows as active is exactly what is
// capable of blocking an edit.
func (d *DB) ActiveRoots() ([]Root, error) {
	rows, err := d.Query(
		`SELECT `+rootCols+` FROM roots
		  WHERE ended_at IS NULL AND last_seen_at > ?
		  ORDER BY registered_at`, RootTTLCutoff())
	if err != nil {
		return nil, serr.Internalf(err, "failed to list roots")
	}
	defer rows.Close()

	out := []Root{}
	for rows.Next() {
		r, err := scanRoot(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *r)
	}
	return out, rows.Err()
}

func (d *DB) GetRoot(rootID string) (*Root, error) {
	return scanRoot(d.QueryRow(
		`SELECT `+rootCols+` FROM roots WHERE root_id = ? AND ended_at IS NULL`, rootID))
}

// RootBySession resolves the root owning a host session label — how a hook
// tells "my own claim" from "someone else's".
func (d *DB) RootBySession(agentKind, sessionLabel string) (*Root, error) {
	if sessionLabel == "" {
		return nil, ErrNoRoot
	}
	return scanRoot(d.QueryRow(
		`SELECT `+rootCols+` FROM roots
		  WHERE agent_kind = ? AND session_label = ? AND ended_at IS NULL AND last_seen_at > ?
		  ORDER BY registered_at DESC LIMIT 1`,
		agentKind, sessionLabel, RootTTLCutoff()))
}

// Heartbeat refreshes a root's liveness. Every registered call does this, so an
// agent that is working never loses its claims to the TTL.
func (d *DB) Heartbeat(rootID string) error {
	res, err := d.Exec(`UPDATE roots SET last_seen_at = ? WHERE root_id = ? AND ended_at IS NULL`, Now(), rootID)
	if err != nil {
		return serr.Internalf(err, "failed to record heartbeat")
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNoRoot
	}
	return nil
}

// DeregisterRoot ends a root and releases everything it held. A clean exit
// should not make others wait out the TTL.
func (d *DB) DeregisterRoot(rootID string) error {
	tx, err := d.Begin()
	if err != nil {
		return serr.Internalf(err, "failed to begin transaction")
	}
	defer tx.Rollback()

	now := Now()
	res, err := tx.Exec(`UPDATE roots SET ended_at = ? WHERE root_id = ? AND ended_at IS NULL`, now, rootID)
	if err != nil {
		return serr.Internalf(err, "failed to deregister root")
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNoRoot
	}
	if _, err := tx.Exec(
		`UPDATE claims SET released_at = ? WHERE root_id = ? AND released_at IS NULL`, now, rootID,
	); err != nil {
		return serr.Internalf(err, "failed to release claims")
	}
	if err := audit(tx, AuditEntry{Actor: rootID, Action: "root_deregister"}); err != nil {
		return serr.Internalf(err, "failed to write audit record")
	}
	if err := tx.Commit(); err != nil {
		return serr.Internalf(err, "failed to commit deregistration")
	}
	return nil
}

// ReapStaleRoots ends roots that went silent long ago. Claims are already
// ignored past RootTTL by the active predicate; this is bookkeeping, run
// opportunistically on context_open, never on a hot path.
func (d *DB) ReapStaleRoots() (int, error) {
	now := NowTime()
	res, err := d.Exec(
		`UPDATE roots SET ended_at = ? WHERE ended_at IS NULL AND last_seen_at < ?`,
		Stamp(now), Stamp(now.Add(-StaleRootAge)))
	if err != nil {
		return 0, serr.Internalf(err, "failed to reap stale roots")
	}
	n, _ := res.RowsAffected()
	return int(n), nil
}
